[cargo]
b = "build"
c = "check"
t = "test"
r = "run"
w = "watch"
rr = "run --release"
rq = "run --quiet"
wr = "watch --quiet --clear --exec \"run --quiet --\""
recursive_example = "rr --example recursions"
space_example = ["run", "--release", "--", "\"command list\""]