[flake]
name = "say_data"

[toolchain]
# profile = "minimal"
channel = "nightly" #"nightly-2023-03-30"
components = [
  "rustc",
  "cargo",
  "rustfmt",
  "rust-analyzer",
  "rust-src",
  "clippy",
  # "miri",
  # "rustc-dev",
  "llvm-tools-preview",
]
targets = [
  "wasm32-unknown-unknown",
  # "x86_64-unknown-linux-musl",
  # "x86_64-unknown-linux-gnu",
  # "aarch64-unknown-linux-musl",
]

[verbosity]
level = "verbose" #[verbose, normal, quiet]

[Server]
PGDATA = "data"
PGLOG = "log/PostgreSQL.log"
PGHOST = "localhost"
PGPORT = 5321
PGDATABASE = "postgres"

[Projects]
[Projects.PRJ1]
DB = "nba"
DIR = "src/nba"
DATA = "assets/nba/data/"

[Projects.PRJ2]
DB = "world"
DIR = "src/world"
INIT = "assets/world.sql"
SOURCE = "https://mysqlcode.com/wp-content/uploads/2023/01/world.zip"


[DatabaseURL]
DB_URL = "postgres://$PGUSER@$PGHOST:$PGPORT/bookstore"
DB_URL_PRJ1 = "postgres://$PGUSER@$PGHOST:$PGPORT/$PRJ1_DB"
DB_URL_PRJ2 = "postgres://$PGUSER@$PGHOST:$PGPORT/$PRJ2_DB"

[alias]
b = "build"
c = "check"
t = "test"
r = "run"
w = "watch"
rr = "run --release"
rq = "run --quiet"
wr = "watch --quiet --clear --exec \"run --quiet --\""
recursive_example = "rr --example recursions"
space_example = ["run", "--release", "--", "\"command list\""]