#!/bin/sh

while [ "$#" -ge 1 ]; do
    case "$1" in
    -f | --file | --toml) [ -f "$2" ] && toml="${2:-$flake_config}" ;;
    -t | --table) table="$2" ;;
    esac
    shift
done

echo "toml: $toml"
echo "table: $table"
